// <auto-generated />
using System;
using Immortality.GameService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Immortality.GameService.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260721135518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Immortality.GameService.Entities.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CreatedAt");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("Immortality.GameService.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CultivationLayer")
                        .HasColumnType("integer");

                    b.Property<int>("CultivationRealm")
                        .HasColumnType("integer");

                    b.Property<int>("CultivationSubLayer")
                        .HasColumnType("integer");

                    b.Property<long>("KarmaAttachment")
                        .HasColumnType("bigint");

                    b.Property<long>("KarmaCausal")
                        .HasColumnType("bigint");

                    b.Property<long>("KarmaEvil")
                        .HasColumnType("bigint");

                    b.Property<long>("KarmaGood")
                        .HasColumnType("bigint");

                    b.Property<long>("KarmaMerit")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MaxSpiritualPower")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("integer");

                    b.Property<int>("MeritPoints")
                        .HasColumnType("integer");

                    b.Property<long>("SpiritualPower")
                        .HasColumnType("bigint");

                    b.Property<int>("SpiritualRoot")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterName")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Immortality.GameService.Entities.PlayerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SnapshotVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SnapshotVersion");

                    b.ToTable("PlayerSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
